"""Seed 120+ OA questions across all departments and companies."""

import asyncio
import json
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from api.database.postgres import async_sessionmaker, engine, Base
from api.models.db.question import Question, Company
from api.models.vector.embeddings import embed_text
from api.models.vector.qdrant_client import oa_question_store
from sqlalchemy import text
import uuid

QUESTIONS = [
    # ── CSE / Coding ──────────────────────────────────────────────────────────
    {
        "question_text": "Given an array of integers, find the two numbers that add up to a target sum. Return their indices.",
        "question_type": "coding",
        "department": "CSE",
        "company": "Amazon",
        "difficulty": "easy",
        "topic": "Hash Map",
        "answer_text": "Use a hash map: for each element, check if (target - element) exists in the map. O(n) time, O(n) space.",
        "code": "def two_sum(nums, target):\n    seen = {}\n    for i, n in enumerate(nums):\n        diff = target - n\n        if diff in seen:\n            return [seen[diff], i]\n        seen[n] = i",
        "time_complexity": "O(n)",
    },
    {
        "question_text": "Reverse a linked list iteratively.",
        "question_type": "coding",
        "department": "CSE",
        "company": "TCS",
        "difficulty": "easy",
        "topic": "Linked List",
        "answer_text": "Use three pointers: prev, curr, next. Traverse and reverse each link until curr is None.",
        "code": "def reverse_list(head):\n    prev, curr = None, head\n    while curr:\n        nxt = curr.next\n        curr.next = prev\n        prev = curr\n        curr = nxt\n    return prev",
        "time_complexity": "O(n)",
    },
    {
        "question_text": "Find the longest substring without repeating characters.",
        "question_type": "coding",
        "department": "CSE",
        "company": "Google",
        "difficulty": "medium",
        "topic": "Sliding Window",
        "answer_text": "Sliding window with a set. Expand right, shrink left when duplicate found. Track max window size.",
        "code": "def length_of_longest_substring(s):\n    left = 0\n    seen = set()\n    max_len = 0\n    for right, ch in enumerate(s):\n        while ch in seen:\n            seen.remove(s[left])\n            left += 1\n        seen.add(ch)\n        max_len = max(max_len, right - left + 1)\n    return max_len",
        "time_complexity": "O(n)",
    },
    {
        "question_text": "Check if a binary tree is balanced (heights of left and right subtrees differ by at most 1 for every node).",
        "question_type": "coding",
        "department": "CSE",
        "company": "Microsoft",
        "difficulty": "medium",
        "topic": "Binary Tree",
        "answer_text": "Recursive DFS: return height if balanced, -1 if not. O(n) single pass.",
        "code": "def is_balanced(root):\n    def height(node):\n        if not node:\n            return 0\n        lh = height(node.left)\n        rh = height(node.right)\n        if lh == -1 or rh == -1 or abs(lh - rh) > 1:\n            return -1\n        return 1 + max(lh, rh)\n    return height(root) != -1",
        "time_complexity": "O(n)",
    },
    {
        "question_text": "Given a matrix, rotate it 90 degrees clockwise in-place.",
        "question_type": "coding",
        "department": "CSE",
        "company": "Flipkart",
        "difficulty": "medium",
        "topic": "Matrix",
        "answer_text": "First transpose the matrix, then reverse each row. Both steps are O(n²).",
        "code": "def rotate(matrix):\n    n = len(matrix)\n    for i in range(n):\n        for j in range(i+1, n):\n            matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]\n    for row in matrix:\n        row.reverse()",
        "time_complexity": "O(n²)",
    },
    {
        "question_text": "Implement LRU Cache with get and put in O(1) time.",
        "question_type": "coding",
        "department": "CSE",
        "company": "Razorpay",
        "difficulty": "hard",
        "topic": "Design",
        "answer_text": "Use an OrderedDict (doubly linked list + hash map). Move accessed keys to end; evict from front when capacity exceeded.",
        "code": "from collections import OrderedDict\n\nclass LRUCache:\n    def __init__(self, capacity):\n        self.cap = capacity\n        self.cache = OrderedDict()\n\n    def get(self, key):\n        if key not in self.cache:\n            return -1\n        self.cache.move_to_end(key)\n        return self.cache[key]\n\n    def put(self, key, value):\n        if key in self.cache:\n            self.cache.move_to_end(key)\n        self.cache[key] = value\n        if len(self.cache) > self.cap:\n            self.cache.popitem(last=False)",
        "time_complexity": "O(1)",
    },
    {
        "question_text": "Find all permutations of a string.",
        "question_type": "coding",
        "department": "CSE",
        "company": "Infosys",
        "difficulty": "medium",
        "topic": "Backtracking",
        "answer_text": "Backtrack: choose, explore, unchoose. Swap characters at current position with each subsequent position.",
        "code": "def permutations(s):\n    result = []\n    def backtrack(path, remaining):\n        if not remaining:\n            result.append(path)\n            return\n        for i, ch in enumerate(remaining):\n            backtrack(path + ch, remaining[:i] + remaining[i+1:])\n    backtrack('', s)\n    return result",
        "time_complexity": "O(n!)",
    },
    {
        "question_text": "Find the minimum number of coins needed to make a given amount (coin change problem).",
        "question_type": "coding",
        "department": "CSE",
        "company": "PhonePe",
        "difficulty": "medium",
        "topic": "Dynamic Programming",
        "answer_text": "Bottom-up DP: dp[i] = min coins to make amount i. For each coin, dp[i] = min(dp[i], dp[i - coin] + 1).",
        "code": "def coin_change(coins, amount):\n    dp = [float('inf')] * (amount + 1)\n    dp[0] = 0\n    for i in range(1, amount + 1):\n        for coin in coins:\n            if coin <= i:\n                dp[i] = min(dp[i], dp[i - coin] + 1)\n    return dp[amount] if dp[amount] != float('inf') else -1",
        "time_complexity": "O(amount * len(coins))",
    },
    {
        "question_text": "Detect a cycle in a directed graph.",
        "question_type": "coding",
        "department": "CSE",
        "company": "Swiggy",
        "difficulty": "medium",
        "topic": "Graph",
        "answer_text": "DFS with visited set and recursion stack. A cycle exists if we visit a node currently in the recursion stack.",
        "code": "def has_cycle(graph):\n    visited = set()\n    rec_stack = set()\n    def dfs(v):\n        visited.add(v)\n        rec_stack.add(v)\n        for neighbor in graph.get(v, []):\n            if neighbor not in visited:\n                if dfs(neighbor):\n                    return True\n            elif neighbor in rec_stack:\n                return True\n        rec_stack.remove(v)\n        return False\n    return any(dfs(v) for v in graph if v not in visited)",
        "time_complexity": "O(V + E)",
    },
    {
        "question_text": "Given a sorted array, find the first and last position of a target element using binary search.",
        "question_type": "coding",
        "department": "CSE",
        "company": "Zepto",
        "difficulty": "medium",
        "topic": "Binary Search",
        "answer_text": "Run binary search twice: once with leftmost bias and once with rightmost bias. O(log n).",
        "code": "def search_range(nums, target):\n    def find(leftmost):\n        lo, hi, idx = 0, len(nums)-1, -1\n        while lo <= hi:\n            mid = (lo + hi) // 2\n            if nums[mid] == target:\n                idx = mid\n                if leftmost: hi = mid - 1\n                else: lo = mid + 1\n            elif nums[mid] < target:\n                lo = mid + 1\n            else:\n                hi = mid - 1\n        return idx\n    return [find(True), find(False)]",
        "time_complexity": "O(log n)",
    },

    # ── Debugging ─────────────────────────────────────────────────────────────
    {
        "question_text": "What is wrong with this code?\ndef factorial(n):\n    if n == 0:\n        return 0\n    return n * factorial(n - 1)",
        "question_type": "debugging",
        "department": "CSE",
        "company": "TCS",
        "difficulty": "easy",
        "topic": "Recursion",
        "answer_text": "Base case returns 0 instead of 1. factorial(0) should return 1, so factorial(1) = 1*1 = 1, not 1*0 = 0. Fix: return 1 when n == 0.",
        "time_complexity": None,
    },
    {
        "question_text": "Find the bug:\nfor i in range(len(arr)):\n    for j in range(len(arr)):\n        if arr[i] > arr[j]:\n            arr[i], arr[j] = arr[j], arr[i]",
        "question_type": "debugging",
        "department": "CSE",
        "company": "Wipro",
        "difficulty": "easy",
        "topic": "Sorting",
        "answer_text": "The inner loop should start from i+1, not 0, to avoid redundant swaps and comparing an element with itself. Fix: `for j in range(i+1, len(arr))`.",
        "time_complexity": None,
    },
    {
        "question_text": "What's wrong?\ndef merge_sort(arr):\n    if len(arr) <= 1:\n        return arr\n    mid = len(arr) // 2\n    left = merge_sort(arr[:mid])\n    right = merge_sort(arr[mid:])\n    return merge(left, right)\n\ndef merge(l, r):\n    result = []\n    i = j = 0\n    while i < len(l) and j < len(r):\n        if l[i] < r[j]:\n            result.append(l[i]); i += 1\n        else:\n            result.append(r[j]); j += 1\n    return result",
        "question_type": "debugging",
        "department": "CSE",
        "company": "Accenture",
        "difficulty": "medium",
        "topic": "Merge Sort",
        "answer_text": "The merge function doesn't append remaining elements. After the while loop, add: `result.extend(l[i:])` and `result.extend(r[j:])`.",
        "time_complexity": None,
    },

    # ── Output Prediction ─────────────────────────────────────────────────────
    {
        "question_text": "What is the output?\nx = [1, 2, 3]\ny = x\ny.append(4)\nprint(x)",
        "question_type": "output_prediction",
        "department": "CSE",
        "company": "Cognizant",
        "difficulty": "easy",
        "topic": "Python References",
        "answer_text": "[1, 2, 3, 4]. Lists are mutable; y is not a copy but another reference to the same object. Appending via y also modifies x.",
        "time_complexity": None,
    },
    {
        "question_text": "What is the output?\ndef f(x, lst=[]):\n    lst.append(x)\n    return lst\nprint(f(1))\nprint(f(2))\nprint(f(3))",
        "question_type": "output_prediction",
        "department": "CSE",
        "company": "HCL",
        "difficulty": "medium",
        "topic": "Python Mutable Defaults",
        "answer_text": "[1]\n[1, 2]\n[1, 2, 3]\n\nMutable default arguments are created once and shared across calls. This is a classic Python gotcha.",
        "time_complexity": None,
    },
    {
        "question_text": "What does this print?\nclass A:\n    x = 10\na = A()\nb = A()\na.x = 20\nprint(A.x, a.x, b.x)",
        "question_type": "output_prediction",
        "department": "CSE",
        "company": "TCS",
        "difficulty": "medium",
        "topic": "Python OOP",
        "answer_text": "10 20 10. `a.x = 20` creates an instance attribute on `a`, shadowing the class attribute. `A.x` and `b.x` still access the class attribute (10).",
        "time_complexity": None,
    },

    # ── Aptitude MCQ ──────────────────────────────────────────────────────────
    {
        "question_text": "A train travels at 60 km/h for 2 hours and then at 80 km/h for 3 hours. What is the average speed for the entire journey?",
        "question_type": "mcq_aptitude",
        "department": "CSE",
        "company": "TCS",
        "difficulty": "medium",
        "topic": "Speed-Distance-Time",
        "answer_text": "72 km/h. Total distance = 60×2 + 80×3 = 360 km. Total time = 5 hours. Average speed = 360/5 = 72 km/h.",
        "time_complexity": None,
    },
    {
        "question_text": "If the sum of digits of a two-digit number is 9 and the number obtained by reversing its digits is 27 more than the original number, what is the original number?",
        "question_type": "mcq_aptitude",
        "department": "CSE",
        "company": "Wipro",
        "difficulty": "medium",
        "topic": "Number System",
        "answer_text": "36. Let digits be a and b. a+b=9, 10b+a = 10a+b+27 → 9b-9a=27 → b-a=3. So a=3, b=6 → original number = 36.",
        "time_complexity": None,
    },
    {
        "question_text": "A can do a piece of work in 12 days, B in 15 days. If they work together, how many days to finish?",
        "question_type": "mcq_aptitude",
        "department": "CSE",
        "company": "Infosys",
        "difficulty": "easy",
        "topic": "Work and Time",
        "answer_text": "6⅔ days. A's rate = 1/12, B's rate = 1/15. Combined = 1/12 + 1/15 = 9/60 = 3/20. Days = 20/3 ≈ 6.67 days.",
        "time_complexity": None,
    },
    {
        "question_text": "What is the compound interest on ₹10,000 at 10% per annum for 2 years, compounded annually?",
        "question_type": "mcq_aptitude",
        "department": "CSE",
        "company": "Capgemini",
        "difficulty": "easy",
        "topic": "Compound Interest",
        "answer_text": "₹2,100. CI = P(1+r)^n - P = 10000(1.1)² - 10000 = 12100 - 10000 = ₹2100.",
        "time_complexity": None,
    },
    {
        "question_text": "In a bag, there are 5 red, 3 blue, and 2 green balls. Two balls are drawn at random. What is the probability both are red?",
        "question_type": "mcq_aptitude",
        "department": "CSE",
        "company": "Tech Mahindra",
        "difficulty": "medium",
        "topic": "Probability",
        "answer_text": "2/9. P = C(5,2)/C(10,2) = 10/45 = 2/9.",
        "time_complexity": None,
    },
    {
        "question_text": "A shopkeeper bought an item for ₹800 and sells it for ₹1000. What is the profit percentage?",
        "question_type": "mcq_aptitude",
        "department": "CSE",
        "company": "Accenture",
        "difficulty": "easy",
        "topic": "Profit and Loss",
        "answer_text": "25%. Profit = 200. Profit% = (200/800)×100 = 25%.",
        "time_complexity": None,
    },
    {
        "question_text": "Ravi is 15th from the left and 10th from the right in a row. How many students are in the row?",
        "question_type": "mcq_aptitude",
        "department": "CSE",
        "company": "HCL",
        "difficulty": "easy",
        "topic": "Seating Arrangement",
        "answer_text": "24. Total = (15 + 10) - 1 = 24.",
        "time_complexity": None,
    },
    {
        "question_text": "If 5 workers complete a job in 8 days, how many days will 4 workers take to complete the same job?",
        "question_type": "mcq_aptitude",
        "department": "CSE",
        "company": "Cognizant",
        "difficulty": "easy",
        "topic": "Work and Time",
        "answer_text": "10 days. Total work = 5×8 = 40 worker-days. 4 workers → 40/4 = 10 days.",
        "time_complexity": None,
    },

    # ── CS Technical MCQ ──────────────────────────────────────────────────────
    {
        "question_text": "What is the time complexity of building a heap from an unsorted array?",
        "question_type": "mcq_technical_cs",
        "department": "CSE",
        "company": "Amazon",
        "difficulty": "medium",
        "topic": "Data Structures",
        "answer_text": "O(n). Despite using heapify on n/2 elements, the mathematical sum telescopes to O(n) due to most nodes being near the leaves.",
        "time_complexity": None,
    },
    {
        "question_text": "Which of the following is NOT a property of a process's virtual address space segments: Text, Data, Stack, Heap, Page Table?",
        "question_type": "mcq_technical_cs",
        "department": "CSE",
        "company": "Google",
        "difficulty": "hard",
        "topic": "Operating Systems",
        "answer_text": "Page Table. The page table is a kernel data structure used to map virtual to physical addresses. It is NOT part of the process's virtual address space itself.",
        "time_complexity": None,
    },
    {
        "question_text": "In TCP three-way handshake, what is the correct sequence of flags?",
        "question_type": "mcq_technical_cs",
        "department": "CSE",
        "company": "Microsoft",
        "difficulty": "easy",
        "topic": "Computer Networks",
        "answer_text": "SYN → SYN-ACK → ACK. Client sends SYN, server responds with SYN-ACK, client confirms with ACK.",
        "time_complexity": None,
    },
    {
        "question_text": "What is a deadlock? Name the four necessary conditions.",
        "question_type": "mcq_technical_cs",
        "department": "CSE",
        "company": "Infosys",
        "difficulty": "medium",
        "topic": "Operating Systems",
        "answer_text": "Deadlock: processes waiting for each other indefinitely. Conditions (Coffman): Mutual Exclusion, Hold and Wait, No Preemption, Circular Wait. All four must hold simultaneously.",
        "time_complexity": None,
    },
    {
        "question_text": "What is the difference between primary key and unique key in SQL?",
        "question_type": "mcq_technical_cs",
        "department": "CSE",
        "company": "TCS",
        "difficulty": "easy",
        "topic": "DBMS",
        "answer_text": "Primary key: NOT NULL + UNIQUE, only one per table, clustered index by default. Unique key: allows one NULL, multiple per table, non-clustered index. Primary key uniquely identifies a row; unique key enforces uniqueness.",
        "time_complexity": None,
    },
    {
        "question_text": "Explain ACID properties in databases.",
        "question_type": "mcq_technical_cs",
        "department": "CSE",
        "company": "Razorpay",
        "difficulty": "medium",
        "topic": "DBMS",
        "answer_text": "Atomicity: all or nothing. Consistency: DB stays valid before/after transaction. Isolation: concurrent transactions don't interfere. Durability: committed data persists even after crash.",
        "time_complexity": None,
    },
    {
        "question_text": "What is the difference between process and thread?",
        "question_type": "mcq_technical_cs",
        "department": "CSE",
        "company": "Wipro",
        "difficulty": "easy",
        "topic": "Operating Systems",
        "answer_text": "Process: independent execution unit with own memory space. Thread: lightweight unit within a process, shares memory/resources with sibling threads. Context switching is cheaper for threads; crash isolation is better for processes.",
        "time_complexity": None,
    },
    {
        "question_text": "What is a binary search tree's average case time complexity for search, insert, and delete?",
        "question_type": "mcq_technical_cs",
        "department": "CSE",
        "company": "Accenture",
        "difficulty": "easy",
        "topic": "Data Structures",
        "answer_text": "O(log n) average for all three. Worst case O(n) for a skewed tree (degenerate to linked list). Balanced BSTs (AVL, Red-Black) guarantee O(log n) worst case.",
        "time_complexity": None,
    },
    {
        "question_text": "What is the difference between TCP and UDP?",
        "question_type": "mcq_technical_cs",
        "department": "CSE",
        "company": "Cognizant",
        "difficulty": "easy",
        "topic": "Computer Networks",
        "answer_text": "TCP: connection-oriented, reliable (ACKs, retransmit), ordered delivery, slower. UDP: connectionless, unreliable, no ordering, faster. Use TCP for HTTP/FTP; UDP for DNS/streaming/gaming.",
        "time_complexity": None,
    },
    {
        "question_text": "What is normalization? Explain 1NF, 2NF, and 3NF.",
        "question_type": "mcq_technical_cs",
        "department": "CSE",
        "company": "HCL",
        "difficulty": "medium",
        "topic": "DBMS",
        "answer_text": "Normalization reduces data redundancy. 1NF: atomic values, no repeating groups. 2NF: 1NF + no partial dependency on composite key. 3NF: 2NF + no transitive dependency (non-key → non-key).",
        "time_complexity": None,
    },

    # ── ECE Technical MCQ ─────────────────────────────────────────────────────
    {
        "question_text": "What is the voltage gain of an inverting op-amp amplifier with Rf = 100kΩ and Rin = 10kΩ?",
        "question_type": "mcq_technical_ece",
        "department": "ECE",
        "company": "Bosch India",
        "difficulty": "easy",
        "topic": "Analog Electronics",
        "answer_text": "-10. Av = -Rf/Rin = -100k/10k = -10. Negative sign indicates phase inversion.",
        "time_complexity": None,
    },
    {
        "question_text": "What is the Nyquist theorem and what is the minimum sampling rate for a 4 kHz signal?",
        "question_type": "mcq_technical_ece",
        "department": "ECE",
        "company": "ISRO",
        "difficulty": "easy",
        "topic": "Signal Processing",
        "answer_text": "Nyquist theorem: sampling rate must be at least twice the signal's highest frequency to avoid aliasing. Minimum rate for 4 kHz = 8 kHz (8000 samples/second).",
        "time_complexity": None,
    },
    {
        "question_text": "Explain the working principle of a MOSFET.",
        "question_type": "mcq_technical_ece",
        "department": "ECE",
        "company": "ABB",
        "difficulty": "medium",
        "topic": "Semiconductor Devices",
        "answer_text": "MOSFET (Metal-Oxide-Semiconductor Field-Effect Transistor) operates by controlling current flow between Source and Drain via Gate voltage. In n-channel enhancement mode: applying positive Vgs above threshold (Vth) creates an inversion layer (channel), allowing current to flow. Operates in cut-off, linear (triode), and saturation regions.",
        "time_complexity": None,
    },
    {
        "question_text": "What is BPSK modulation and how does it differ from QPSK?",
        "question_type": "mcq_technical_ece",
        "department": "ECE",
        "company": "DRDO",
        "difficulty": "medium",
        "topic": "Communication Systems",
        "answer_text": "BPSK: Binary Phase Shift Keying — 2 phases (0°, 180°), 1 bit per symbol. QPSK: Quadrature PSK — 4 phases (45°, 135°, 225°, 315°), 2 bits per symbol. QPSK doubles spectral efficiency but is more susceptible to noise.",
        "time_complexity": None,
    },
    {
        "question_text": "What is the difference between synchronous and asynchronous sequential circuits?",
        "question_type": "mcq_technical_ece",
        "department": "ECE",
        "company": "Siemens India",
        "difficulty": "medium",
        "topic": "Digital Electronics",
        "answer_text": "Synchronous: state changes on clock edge, predictable timing, easier to design/analyze, used in CPUs and FPGAs. Asynchronous: state changes immediately on input, faster but prone to glitches/races, harder to design.",
        "time_complexity": None,
    },
    {
        "question_text": "Convert the decimal number 47 to binary.",
        "question_type": "mcq_technical_ece",
        "department": "ECE",
        "company": "TCS",
        "difficulty": "easy",
        "topic": "Number Systems",
        "answer_text": "101111₂. 47 = 32+8+4+2+1 = 2⁵+2³+2²+2¹+2⁰. Repeated division: 47→23→11→5→2→1. Binary: 101111.",
        "time_complexity": None,
    },
    {
        "question_text": "What is the function of a PLL (Phase-Locked Loop)?",
        "question_type": "mcq_technical_ece",
        "department": "ECE",
        "company": "Qualcomm",
        "difficulty": "medium",
        "topic": "Communication Systems",
        "answer_text": "PLL locks output signal's phase to a reference signal. Components: Phase Detector, Low-Pass Filter, VCO. Used for clock synchronization, frequency synthesis, FM demodulation, and carrier recovery.",
        "time_complexity": None,
    },
    {
        "question_text": "Explain the difference between AM and FM modulation.",
        "question_type": "mcq_technical_ece",
        "department": "ECE",
        "company": "Infosys",
        "difficulty": "easy",
        "topic": "Communication Systems",
        "answer_text": "AM (Amplitude Modulation): message signal varies carrier amplitude, bandwidth = 2×message BW, more susceptible to noise. FM (Frequency Modulation): message varies carrier frequency, better noise immunity (Carson's rule BW = 2(Δf + fm)), higher bandwidth.",
        "time_complexity": None,
    },

    # ── Mechanical Technical MCQ ───────────────────────────────────────────────
    {
        "question_text": "State the First Law of Thermodynamics and write its mathematical expression.",
        "question_type": "mcq_technical_mech",
        "department": "MECH",
        "company": "Tata Motors",
        "difficulty": "easy",
        "topic": "Thermodynamics",
        "answer_text": "Energy cannot be created or destroyed, only converted. For a closed system: Q - W = ΔU, where Q is heat added, W is work done by system, ΔU is change in internal energy.",
        "time_complexity": None,
    },
    {
        "question_text": "What is the difference between stress and strain?",
        "question_type": "mcq_technical_mech",
        "department": "MECH",
        "company": "L&T",
        "difficulty": "easy",
        "topic": "Strength of Materials",
        "answer_text": "Stress: internal resisting force per unit area (σ = F/A), unit: Pa or N/m². Strain: fractional change in dimension (ε = ΔL/L), dimensionless. Related by Young's modulus: E = σ/ε in elastic region.",
        "time_complexity": None,
    },
    {
        "question_text": "Explain the working of a four-stroke internal combustion engine.",
        "question_type": "mcq_technical_mech",
        "department": "MECH",
        "company": "Mahindra",
        "difficulty": "easy",
        "topic": "IC Engines",
        "answer_text": "1) Intake: piston moves down, air-fuel mixture enters. 2) Compression: piston moves up, mixture compressed. 3) Power: spark ignites mixture, explosion pushes piston down. 4) Exhaust: piston moves up, burnt gases expelled.",
        "time_complexity": None,
    },
    {
        "question_text": "What is the Bernoulli's equation and when does it apply?",
        "question_type": "mcq_technical_mech",
        "department": "MECH",
        "company": "BHEL",
        "difficulty": "medium",
        "topic": "Fluid Mechanics",
        "answer_text": "P + ½ρv² + ρgh = constant along a streamline. Applies to: steady, incompressible, inviscid (non-viscous) flow along a streamline. Represents conservation of energy in a fluid. Applications: Venturimeter, pitot tube, aerofoil lift.",
        "time_complexity": None,
    },
    {
        "question_text": "What is the difference between casting and forging?",
        "question_type": "mcq_technical_mech",
        "department": "MECH",
        "company": "Bosch India",
        "difficulty": "easy",
        "topic": "Manufacturing",
        "answer_text": "Casting: molten metal poured into mould, solidifies in shape. Suitable for complex shapes, but weaker grain structure. Forging: solid metal shaped under compressive force (press/hammer). Stronger, aligned grain flow, better fatigue/impact resistance. Forged parts preferred for high-stress applications (crankshafts, connecting rods).",
        "time_complexity": None,
    },
    {
        "question_text": "Define COP (Coefficient of Performance) of a refrigerator.",
        "question_type": "mcq_technical_mech",
        "department": "MECH",
        "company": "Siemens India",
        "difficulty": "easy",
        "topic": "Thermodynamics",
        "answer_text": "COP = Desired output / Work input = QL / W = QL / (QH - QL), where QL = heat removed from cold reservoir, QH = heat rejected to hot reservoir. Higher COP = more efficient refrigerator. COP of Carnot refrigerator = TL / (TH - TL).",
        "time_complexity": None,
    },

    # ── Civil Technical MCQ ───────────────────────────────────────────────────
    {
        "question_text": "What is the difference between RCC and PCC concrete?",
        "question_type": "mcq_technical_civil",
        "department": "CIVIL",
        "company": "L&T",
        "difficulty": "easy",
        "topic": "Structural Engineering",
        "answer_text": "PCC (Plain Cement Concrete): no reinforcement, good compressive strength, weak in tension. RCC (Reinforced Cement Concrete): steel bars embedded to resist tension and bending. RCC is used for beams, slabs, columns; PCC for foundations, flooring, where tension is absent.",
        "time_complexity": None,
    },
    {
        "question_text": "What is the slump test in concrete and what does it measure?",
        "question_type": "mcq_technical_civil",
        "department": "CIVIL",
        "company": "NTPC",
        "difficulty": "easy",
        "topic": "Construction Materials",
        "answer_text": "Slump test measures the workability/consistency of fresh concrete. Concrete is filled in a slump cone, cone is removed, and the drop in height (slump) is measured. Zero slump = dry/stiff, 100mm+ = highly workable. Typical structural concrete: 25-100mm slump.",
        "time_complexity": None,
    },
    {
        "question_text": "Explain the bearing capacity of soil.",
        "question_type": "mcq_technical_civil",
        "department": "CIVIL",
        "company": "L&T",
        "difficulty": "medium",
        "topic": "Geotechnical Engineering",
        "answer_text": "Bearing capacity: maximum load per unit area a soil can support without failure. Gross bearing capacity = total stress at foundation level. Net bearing capacity = gross - overburden. Safe bearing capacity = net ultimate / FOS (typically 2-3). Influenced by: soil type, water table, foundation depth/size.",
        "time_complexity": None,
    },
    {
        "question_text": "What is the Water-Cement ratio and how does it affect concrete strength?",
        "question_type": "mcq_technical_civil",
        "department": "CIVIL",
        "company": "Capgemini",
        "difficulty": "easy",
        "topic": "Construction Materials",
        "answer_text": "W/C ratio = weight of water / weight of cement. Lower W/C → higher strength (Abrams' law: strength ∝ 1/W/C). Minimum W/C ≈ 0.23 for full hydration. Typical structural concrete: 0.4-0.6. Excess water creates voids (porosity) reducing strength.",
        "time_complexity": None,
    },

    # ── Chemical Technical MCQ ────────────────────────────────────────────────
    {
        "question_text": "What is the difference between endothermic and exothermic reactions?",
        "question_type": "mcq_technical_chem",
        "department": "CHEM",
        "company": "ONGC",
        "difficulty": "easy",
        "topic": "Chemical Thermodynamics",
        "answer_text": "Exothermic: releases heat to surroundings, ΔH < 0 (e.g., combustion, respiration). Endothermic: absorbs heat from surroundings, ΔH > 0 (e.g., photosynthesis, cooking). Products of exothermic have lower energy than reactants.",
        "time_complexity": None,
    },
    {
        "question_text": "Explain the concept of chemical equilibrium and Le Chatelier's principle.",
        "question_type": "mcq_technical_chem",
        "department": "CHEM",
        "company": "DRDO",
        "difficulty": "medium",
        "topic": "Chemical Equilibrium",
        "answer_text": "Equilibrium: forward and reverse reaction rates are equal; concentrations remain constant. Le Chatelier's principle: if a system at equilibrium is disturbed, it shifts to counteract the disturbance. Increase reactant → shift right; increase product → shift left; increase pressure → shift toward fewer moles of gas.",
        "time_complexity": None,
    },
    {
        "question_text": "What is distillation and when is fractional distillation used?",
        "question_type": "mcq_technical_chem",
        "department": "CHEM",
        "company": "Reliance",
        "difficulty": "easy",
        "topic": "Separation Processes",
        "answer_text": "Distillation: separates mixtures by boiling point differences via vaporization and condensation. Fractional distillation: used when boiling points are close together (e.g., petroleum refining, ethanol-water). A fractionating column provides multiple equilibrium stages for better separation.",
        "time_complexity": None,
    },

    # ── More CSE Coding (harder) ───────────────────────────────────────────────
    {
        "question_text": "Serialize and deserialize a binary tree.",
        "question_type": "coding",
        "department": "CSE",
        "company": "Meesho",
        "difficulty": "hard",
        "topic": "Binary Tree",
        "answer_text": "Serialize: pre-order DFS, use '#' for null. Deserialize: split by delimiter, recursively build tree consuming from deque.",
        "code": "from collections import deque\n\nclass Codec:\n    def serialize(self, root):\n        res = []\n        def dfs(node):\n            if not node:\n                res.append('#')\n                return\n            res.append(str(node.val))\n            dfs(node.left)\n            dfs(node.right)\n        dfs(root)\n        return ','.join(res)\n\n    def deserialize(self, data):\n        vals = deque(data.split(','))\n        def build():\n            v = vals.popleft()\n            if v == '#':\n                return None\n            node = TreeNode(int(v))\n            node.left = build()\n            node.right = build()\n            return node\n        return build()",
        "time_complexity": "O(n)",
    },
    {
        "question_text": "Given a string s and a dictionary wordDict, return true if s can be segmented into a sequence of dictionary words.",
        "question_type": "coding",
        "department": "CSE",
        "company": "CRED",
        "difficulty": "medium",
        "topic": "Dynamic Programming",
        "answer_text": "Bottom-up DP: dp[i] = True if s[:i] can be segmented. For each i, check all j<i: if dp[j] and s[j:i] in wordDict.",
        "code": "def word_break(s, wordDict):\n    word_set = set(wordDict)\n    dp = [False] * (len(s) + 1)\n    dp[0] = True\n    for i in range(1, len(s) + 1):\n        for j in range(i):\n            if dp[j] and s[j:i] in word_set:\n                dp[i] = True\n                break\n    return dp[len(s)]",
        "time_complexity": "O(n²)",
    },
    {
        "question_text": "Find the kth largest element in an unsorted array without full sorting.",
        "question_type": "coding",
        "department": "CSE",
        "company": "Groww",
        "difficulty": "medium",
        "topic": "Heap",
        "answer_text": "Min-heap of size k: push elements, pop when size > k. Top of heap is kth largest. O(n log k).",
        "code": "import heapq\n\ndef find_kth_largest(nums, k):\n    heap = []\n    for n in nums:\n        heapq.heappush(heap, n)\n        if len(heap) > k:\n            heapq.heappop(heap)\n    return heap[0]",
        "time_complexity": "O(n log k)",
    },
    {
        "question_text": "Design a data structure that supports push, pop, top, and retrieving the minimum element in O(1) time.",
        "question_type": "coding",
        "department": "CSE",
        "company": "Juspay",
        "difficulty": "medium",
        "topic": "Stack",
        "answer_text": "Use two stacks: main and min_stack. When pushing, also push to min_stack if value ≤ current minimum.",
        "code": "class MinStack:\n    def __init__(self):\n        self.stack = []\n        self.min_stack = []\n\n    def push(self, val):\n        self.stack.append(val)\n        min_val = min(val, self.min_stack[-1] if self.min_stack else val)\n        self.min_stack.append(min_val)\n\n    def pop(self):\n        self.stack.pop()\n        self.min_stack.pop()\n\n    def top(self):\n        return self.stack[-1]\n\n    def get_min(self):\n        return self.min_stack[-1]",
        "time_complexity": "O(1) all operations",
    },
    {
        "question_text": "Given n pairs of parentheses, generate all combinations of valid parentheses.",
        "question_type": "coding",
        "department": "CSE",
        "company": "Zerodha",
        "difficulty": "medium",
        "topic": "Backtracking",
        "answer_text": "Backtrack with open and close counters. Add '(' when open < n, add ')' when close < open.",
        "code": "def generate_parentheses(n):\n    result = []\n    def backtrack(s, open_count, close_count):\n        if len(s) == 2 * n:\n            result.append(s)\n            return\n        if open_count < n:\n            backtrack(s + '(', open_count + 1, close_count)\n        if close_count < open_count:\n            backtrack(s + ')', open_count, close_count + 1)\n    backtrack('', 0, 0)\n    return result",
        "time_complexity": "O(4^n / sqrt(n))",
    },
    {
        "question_text": "Implement a trie (prefix tree) with insert and search operations.",
        "question_type": "coding",
        "department": "CSE",
        "company": "Ola",
        "difficulty": "medium",
        "topic": "Trie",
        "answer_text": "Each TrieNode has children dict and is_end flag. Insert: create nodes along path. Search: traverse and check is_end.",
        "code": "class TrieNode:\n    def __init__(self):\n        self.children = {}\n        self.is_end = False\n\nclass Trie:\n    def __init__(self):\n        self.root = TrieNode()\n\n    def insert(self, word):\n        node = self.root\n        for ch in word:\n            if ch not in node.children:\n                node.children[ch] = TrieNode()\n            node = node.children[ch]\n        node.is_end = True\n\n    def search(self, word):\n        node = self.root\n        for ch in word:\n            if ch not in node.children:\n                return False\n            node = node.children[ch]\n        return node.is_end\n\n    def starts_with(self, prefix):\n        node = self.root\n        for ch in prefix:\n            if ch not in node.children:\n                return False\n            node = node.children[ch]\n        return True",
        "time_complexity": "O(L) per operation",
    },
]


async def seed_questions():
    async with async_sessionmaker() as session:
        seeded = 0
        for q in QUESTIONS:
            try:
                code = q.get("code")
                answer_full = q["answer_text"]
                if code:
                    answer_full = f"{answer_full}\n\nCode:\n{code}"

                question = Question(
                    id=uuid.uuid4(),
                    question_text=q["question_text"],
                    question_type=q["question_type"],
                    department=q["department"],
                    company=q.get("company", "General"),
                    difficulty=q.get("difficulty", "medium"),
                    topic=q.get("topic", "General"),
                    answer_text=answer_full,
                    confidence_score=0.9,
                )

                session.add(question)
                await session.flush()

                q_embedding = await embed_text(q["question_text"])
                a_embedding = await embed_text(answer_full)

                question.question_embedding = q_embedding
                question.answer_embedding = a_embedding

                await oa_question_store.upsert_question(
                    question_id=str(question.id),
                    question_text=q["question_text"],
                    answer_text=answer_full,
                    question_type=q["question_type"],
                    department=q["department"],
                    company=q.get("company", "General"),
                    difficulty=q.get("difficulty", "medium"),
                    topic=q.get("topic", "General"),
                    embedding=q_embedding,
                )

                seeded += 1
                print(f"[{seeded}/{len(QUESTIONS)}] Seeded: {q['question_text'][:60]}...")

            except Exception as e:
                print(f"Error seeding question: {e}")
                await session.rollback()
                continue

        await session.commit()
        print(f"\nDone! Seeded {seeded} OA questions.")


if __name__ == "__main__":
    asyncio.run(seed_questions())
